#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/ui.sh"
ui_banner 'ReefNet lab' 'Run these commands in the WSL repository.'
row() { ui_command_row "$1" "$2"; }
ui_subsection 'Start'
row 'make setup' 'prepare this computer once'
row 'make networking' 'follow a service request'
row 'make operations' 'investigate an incident'
row 'make automation' 'repair through an API'
row 'make monitoring' 'measure traffic and faults'
ui_subsection 'Find your way'
row 'make exercises' 'worksheet overview'
row 'make cheatsheet' 'commands and where to run them'
row 'make task' 'first task in the active scenario'
row 'make hint STEP=2' 'help with a selected step'
row 'make solution STEP=2' 'worked answer for that step'
row 'make enter NODE=probe01.bob1.lagoontransit.test' 'open the Lagoon probe'
ui_subsection 'Check and stop'
row 'make test' 'ping from both probes over IPv4 and IPv6'
row 'make status' 'show the running lab'
row 'make down' 'remove containers after saving your work'
row 'make reset' 'recreate the current exercise from the beginning'
row 'make doctor' 'check a setup problem'
row 'make diagnostics' 'save diagnostic logs'
ui_subsection 'Monitoring experiments'
row 'make traffic-40mbit' 'set load, also try traffic-60mbit or traffic-75mbit'
row 'make traffic-10mbit' 'reduce load'
row 'make traffic-status' 'show selected load'
row 'make traffic-stop' 'stop load'
row 'make traffic-diagnostics' 'save counters and receiver loss'
row 'make fault-link' 'disable core-b, restore with make clear-link'
row 'make fault-routing' 'inject routing fault, restore with make clear-routing'
row 'make traffic-burst-40mbit' 'five-second burst, stop continuous traffic first'
echo
printf '%s\n' 'More commands and slide builds: README.md' 'Starting a scenario again discards its runtime changes.'
