#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/ui.sh"
ui_banner 'AI5049 Classroom Lab · BOB1' 'Networking · Operations · Automation · Monitoring'
ui_subsection 'First time'
printf '  %-20s %s\n' 'make setup' 'validate the workstation and all course workflows'
printf '  %-20s %s\n' 'make course-check' 'rerun every course workflow on a prepared workstation'
ui_subsection 'Course days'
printf '  %-20s %s\n' 'make networking' 'healthy baseline for Networking 101'
printf '  %-20s %s\n' 'make operations' 'IPv4 export incident'
printf '  %-20s %s\n' 'make automation' 'same incident through NetBox/gNMI'
printf '  %-20s %s\n' 'make monitoring' 'healthy network + telemetry + traffic'
ui_subsection 'Enter a node by FQDN'
printf '  %s\n' 'make enter NODE=probe01.bob1.lagoontransit.test'
printf '  %s\n' 'make enter NODE=operations01.bob1.reefnet.test'
printf '  %s\n' 'make enter NODE=edge01.bob1.reefnet.test'
ui_subsection 'Controlled faults'
printf '  %-20s %s\n' 'make fault-routing' 'IPv4 export toward Lagoon Transit'
printf '  %-20s %s\n' 'make fault-link' 'ReefNet core-b link down'
printf '  %-20s %s\n' 'make healthy' 'return to the known healthy baseline'
ui_subsection 'Traffic load'
printf '  %-27s %s\n' 'make traffic-10mbit' '10 Mbit/s · light baseline'
printf '  %-27s %s\n' 'make traffic-25mbit' '25 Mbit/s · unconstrained'
printf '  %-27s %s\n' 'make traffic-40mbit' '40 Mbit/s · below transit capacity'
printf '  %-27s %s\n' 'make traffic-50mbit' '50 Mbit/s · transit capacity boundary'
printf '  %-27s %s\n' 'make traffic-60mbit' '60 Mbit/s · transit congestion expected'
printf '  %-27s %s\n' 'make traffic-75mbit' '75 Mbit/s · stronger congestion, below simulator packet-rate ceiling'
printf '  %-27s %s\n' 'make traffic-burst-40mbit' 'standalone 5 second burst below the transit limit'
printf '  %-27s %s\n' 'make traffic-status' 'show the current offered load'
printf '  %-27s %s\n' 'make traffic-stop' 'stop the traffic generator'
ui_info 'Capacity model: customer handoff 100 Mbit/s, each transit handoff 50 Mbit/s.'
ui_info 'Traffic levels stay below the SR Linux container simulation packet-rate ceiling.'
ui_subsection 'Control'
printf '  %-20s %s\n' 'make status' 'inspect the running lab'
printf '  %-20s %s\n' 'make test' 'end-to-end IPv4/IPv6 reachability'
printf '  %-20s %s\n' 'make reset' 'rebuild this course-day state'
printf '  %-20s %s\n' 'make down' 'stop the lab, keep prepared NetBox data'
printf '  %-20s %s\n' 'make clean' 'remove lab state + NetBox data, keep base images'
printf '  %-20s %s\n' 'make next' 'show the current course-day guide'
echo
